#define MTK_EOF                          1
#define MTK_EOL                          2
#define MTK_ID                           3
#define MTK_COLON                        4
#define MCKW_SHOW                        5
#define MCKW_SET                         6
#define MTK_OPEQUAL                      7
#define MCKW_EXEC                        8
#define MSTR_LITERAL                     9
#define MCKW_STOP                       10
#define MTK_LBRACKET                    11
#define MTK_RBRACKET                    12
#define MTK_COMMA                       13
#define MTK_REGISTER                    14
#define MCKW_MEM                        15
#define MTK_OPENP                       16
#define MTK_CLOSEP                      17
#define MKW_BYTE                        18
#define MKW_HWORD                       19
#define MKW_WORD                        20
#define MCKW_HEX                        21
#define MCKW_DEC                        22
#define MCKW_SIGNED                     23
#define MCKW_UNSIGNED                   24
#define MCKW_BINARY                     25
#define MTK_DEC_CONSTANT                26
#define MTK_OP_MINUS                    27
#define MTK_HEX_CONSTANT                28
#define MTK_BIN_CONSTANT                29
