#define XTK_EOF                          1
#define XTK_EOL                          2
#define XTK_ID                           3
#define XTK_COLON                        4
#define XCKW_SET                         5
#define XTK_OP_EQUAL                     6
#define XCKW_SHOW                        7
#define XCKW_EXEC                        8
#define XSTR_LITERAL                     9
#define XCKW_STOP                       10
#define XTK_LBRACKET                    11
#define XTK_RBRACKET                    12
#define XTK_COMMA                       13
#define TK_EFLAGS                       14
#define XCKW_HEX                        15
#define XCKW_SIGNED                     16
#define XCKW_UNSIGNED                   17
#define XCKW_BIN                        18
#define XCKW_OCT                        19
#define XCKW_DEC                        20
#define XKW_DEC                         21
#define XKW_MOV                         22
#define XKW_MOVSX                       23
#define XKW_MOVZX                       24
#define XKW_PUSH                        25
#define XKW_POP                         26
#define XKW_LEA                         27
#define XKW_ADD                         28
#define XKW_SUB                         29
#define XKW_CMP                         30
#define XKW_TEST                        31
#define XKW_INC                         32
#define XKW_IMUL                        33
#define XKW_MUL                         34
#define XKW_DIV                         35
#define XKW_IDIV                        36
#define XKW_AND                         37
#define XKW_OR                          38
#define XKW_XOR                         39
#define XKW_NOT                         40
#define XKW_NEG                         41
#define XKW_SHL                         42
#define XKW_SHR                         43
#define XKW_JMP                         44
#define XKW_JE                          45
#define XKW_JNE                         46
#define XKW_JZ                          47
#define XKW_JNZ                         48
#define XKW_JG                          49
#define XKW_JGE                         50
#define XKW_JL                          51
#define XKW_JLE                         52
#define XKW_JB                          53
#define XKW_JNAE                        54
#define XKW_JC                          55
#define XKW_JNB                         56
#define XKW_JAE                         57
#define XKW_JNC                         58
#define XKW_JBE                         59
#define XKW_JNA                         60
#define XKW_JA                          61
#define XKW_JNBE                        62
#define XKW_CALL                        63
#define XKW_RET                         64
#define XKW_CDQ                         65
#define TK_AL                           66
#define TK_AH                           67
#define TK_BL                           68
#define TK_BH                           69
#define TK_CL                           70
#define TK_CH                           71
#define TK_DL                           72
#define TK_DH                           73
#define TK_AX                           74
#define TK_BX                           75
#define TK_CX                           76
#define TK_DX                           77
#define TK_EAX                          78
#define TK_EBX                          79
#define TK_ECX                          80
#define TK_EDX                          81
#define TK_ESI                          82
#define TK_EDI                          83
#define TK_ESP                          84
#define TK_EBP                          85
#define XKW_BYTE                        86
#define XKW_WORD                        87
#define XKW_DWORD                       88
#define XKW_PTR                         89
#define XTK_OP_MULT                     90
#define XTK_OP_PLUS                     91
#define XTK_OP_MINUS                    92
#define XTK_DEC_CONSTANT                93
#define XTK_HEX_CONSTANT                94
#define XTK_BIN_CONSTANT                95
#define XTK_OCT_CONSTANT                96
